import { z } from "zod";

export const prepCardSchema = z.object({
  id: z.string(),
  question: z.string().min(1),
  key_points: z.array(z.string()).min(1).max(8),
  sample_answer: z.string().min(50),
  tips: z.string(),
  confidence_level: z.enum(["low", "medium", "high"]),
  references_cv: z.array(z.string()),
});

export const prepSectionSchema = z.object({
  id: z.string(),
  title: z.string().min(1),
  icon: z.string().min(1),
  summary: z.string(),
  cards: z.array(prepCardSchema).min(1).max(10),
});

export const prepGuideSchema = z.object({
  meta: z.object({
    role: z.string().min(1),
    company: z.string().min(1),
    estimated_prep_time_minutes: z.number().int().min(10).max(180),
    /** True when prep shipped with at least one section failed (partial mode).
     *  Set by runStageB when >=3 sections succeed but <5. */
    partial: z.boolean().optional(),
    /** Section kinds that failed when partial=true. Surface via UI banner;
     *  future "regenerate just this section" flow can read this list. */
    failed_sections: z.array(z.string()).optional(),
  }),
  sections: z.array(prepSectionSchema).min(0).max(7),
});

export type PrepGuide = z.infer<typeof prepGuideSchema>;
export type PrepSection = z.infer<typeof prepSectionSchema>;
export type PrepCard = z.infer<typeof prepCardSchema>;

export const atsKeywordSchema = z.object({
  keyword: z.string().min(1),
  found: z.boolean(),
  context: z.string().optional(),
});

export const atsFixSchema = z.object({
  priority: z.number().int().min(1).max(10),
  gap: z.string().min(1),
  original_cv_language: z.string(),
  jd_language: z.string().min(1),
  suggested_rewrite: z.string().min(20),
});

export const atsAnalysisSchema = z.object({
  score: z.number().int().min(0).max(100),
  title_match: z.object({
    cv_title: z.string(),
    jd_title: z.string(),
    match_score: z.number().int().min(0).max(100),
  }),
  keyword_analysis: z.object({
    critical: z.array(atsKeywordSchema).min(0).max(30),
    high: z.array(atsKeywordSchema).min(0).max(40),
    medium: z.array(atsKeywordSchema).min(0).max(40),
  }),
  top_fixes: z.array(atsFixSchema).min(1).max(7),
  overall_assessment: z.string().min(30),
});

export type AtsAnalysis = z.infer<typeof atsAnalysisSchema>;
export type AtsKeyword = z.infer<typeof atsKeywordSchema>;
export type AtsFix = z.infer<typeof atsFixSchema>;

export const companyIntelSchema = z.object({
  overview: z.string().min(20).max(2000),
  recent_developments: z
    .array(
      z.object({
        headline: z.string().min(1).max(200),
        why_it_matters: z.string().min(10).max(400),
        // source_url removed: Gemini grounding emits Vertex AI redirect URLs
        // that often run thousands of chars and break JSON parsing. Citations
        // are better surfaced via the model's grounding metadata if needed.
        source_url: z.string().nullable().optional(),
      }),
    )
    .min(0)
    .max(6),
  key_people: z
    .array(
      z.object({
        name: z.string().min(1).max(120),
        role: z.string().min(1).max(120),
        background_snippet: z.string().min(1).max(400),
      }),
    )
    .min(0)
    .max(5),
  culture_signals: z.array(z.string().min(1).max(300)).min(0).max(6),
  strategic_context: z.string().min(20).max(2000),
  questions_this_creates: z.array(z.string().min(5).max(400)).min(0).max(4),
});

export type CompanyIntel = z.infer<typeof companyIntelSchema>;

export const cvRewriteSchema = z.object({
  markdown: z.string().min(200).max(20000),
  summary_of_changes: z.array(z.string().min(5).max(300)).min(1).max(40),
  preserved_facts: z.array(z.string().min(3).max(300)).min(0).max(60),
});

export type CvRewrite = z.infer<typeof cvRewriteSchema>;

/**
 * Salary benchmark for the role+company combo, rendered as the 4th card on
 * the prep Overview screen. Generated by Stage Salary in the AI pipeline
 * via Gemini with Google Search grounding (fallback to ungrounded training
 * knowledge if grounding fails).
 *
 * Conservative bounds:
 *   - all amounts in R$ (full reais, not centavos) — display as-is
 *   - max(1_000_000) caps absurd outputs (CEO of unicorn would be the upper
 *     bound, anything higher is hallucination)
 *   - notes/region/employment_type fields keep enough qualitative context
 *     that user understands what the number represents
 */
export const salaryBenchmarkSchema = z.object({
  seniority: z.enum([
    "estagio",
    "junior",
    "pleno",
    "senior",
    "especialista",
    "lideranca",
    "nao_identificado",
  ]),
  min_brl: z.number().int().min(0).max(1_000_000),
  median_brl: z.number().int().min(0).max(1_000_000),
  max_brl: z.number().int().min(0).max(1_000_000),
  currency: z.literal("BRL"),
  employment_type_hint: z.string().max(200).optional(),
  region_hint: z.string().min(1).max(200),
  notes: z.string().min(10).max(500),
  confidence: z.enum(["low", "medium", "high"]),
});

export type SalaryBenchmark = z.infer<typeof salaryBenchmarkSchema>;
